version: '3.4'

services:

  app:
    container_name: eduamp-app
    image: eduamp:latest
    restart: unless-stopped
    ports: 
      - "8080:8080"
    env_file: 
      - ./app.env
    depends_on:
      - db
    networks:
      eduamp_network:
        aliases:
          - eduamp_service
          
  db:
    container_name: eduamp-mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file: 
      - mysql.env
    networks:
      eduamp_network:
        aliases:
          - eduamp_service

networks:
  eduamp_network:
